const htmlmin = require('html-minifier-terser');
const { IMG_PATTERN } = require('./config');

/**
 *
 * @param {import('@11ty/eleventy').UserConfig} config
 * @returns
 */
module.exports = (config) => {
	config.addPassthroughCopy(`src/sites/**/${IMG_PATTERN}`);
	config.addPassthroughCopy('src/styles');
	config.addPassthroughCopy('src/scripts');

	config.addWatchTarget('src/styles');
	config.addWatchTarget('src/scripts');

	config.addFilter('parseDate', (date) => {
		const formatter = Intl.DateTimeFormat('ru');
		return formatter.format(new Date(date));
	});

	config.addFilter('year', (date) => {
		return new Date(date).getFullYear();
	});

	config.addFilter('map', (list, key) => {
		if (!Array.isArray(list)) {
			throw Error('map only for arrays');
		}
		return list.map((item) => item[key]);
	});

	config.setServerOptions({
		liveReload: true,
	});

	config.addTransform('htmlmin', (content, outputPath) => {
		if (outputPath && outputPath.endsWith('.html')) {
			const result = htmlmin.minify(content, {
				collapseBooleanAttributes: true,
				collapseWhitespace: true,
				removeComments: true,
				decodeEntities: true,
				includeAutoGeneratedTags: true,
			});

			return result;
		}

		return content;
	});

	return {
		dir: {
			input: 'src',
			output: 'dist',
			data: 'data',
			includes: 'includes',
			layouts: 'layouts',
		},
		htmlTemplateEngine: 'njk',
		dataTemplateEngine: 'njk',
	};
};
