const htmlmin = require("html-minifier-terser");

const baseConfig = require("./eleventy.config.js");

/**
 *
 * @param {import('@11ty/eleventy').UserConfig} config
 * @returns
 */
module.exports = (config) => {
	const result = baseConfig(config);

	config.addTransform("htmlmin", (content, outputPath) => {
		if (outputPath && outputPath.endsWith(".html")) {
			const result = htmlmin.minify(content, {
				collapseBooleanAttributes: true,
				collapseWhitespace: true,
				removeComments: true,
				decodeEntities: true,
				includeAutoGeneratedTags: true,
			});

			return result;
		}

		return content;
	});

	return result;
};
